# Generated by Django 4.1.7 on 2023-04-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 9, 17, 50, 35, 836094, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='place',
            name='isBookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
