# Generated by Django 4.1.7 on 2023-04-11 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
