# Generated by Django 4.1.7 on 2023-05-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-updated_at']},
        ),
    ]
