stages:
  - build
  - deploy

client:build:
  stage: build
  image: node:18
  script:
    - cd client
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

client:deploy:
  stage: deploy
  image: node:18
  needs: ['client:build']
  script: echo "Not implemented yet"
  environment: production

server:build:
  stage: build
  image: python:3.9
  script:
    - source ./traveller-env/bin/activate
    - cd server
    - pip3 install -r requirements.txt
  artifacts:
    paths:
      - .env

server:deploy:
  stage: deploy
  image: python:3.9
  needs: ['server:build']
  script: echo "Not implemented yet"
  environment: production
