stages:
  - build

build_frontend:
  stage: build
  image: node:18
  script:
    - cd client
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

build_backend:
  stage: build
  image: python:3.9
  script:
    - source ./traveller-env/bin/activate
    - cd server
    - pip3 install -r requirements.txt
  artifacts:
    paths:
      - .env
