stages:
  - build_client_stage
  # - deploy_client_stage
  - build_server_stage
  # - deploy_server_stage

client:build:
  stage: build_client_stage
  image: node:18
  script:
    - cd client
    - yarn install
    - yarn build
  artifacts:
    paths:
      - client/dist/

# client:deploy:
#   stage: deploy_client_stage
#   image: debian:bullseye
#   environment: production
#   script:
#     - apt update
#     - apt install sudo -y
#     - sudo apt install sshpass -y
#     - sudo sshpass -p $DEPLOY_SERVER_PW scp -r client/dist/* $DEPLOY_SERVER_USER@$DEPLOY_SERVER_ADDRESS:/home/mipu7431

server:build:
  stage: build_server_stage
  image: python:3.9
  script:
    - source ./traveller-env/bin/activate
    - cd server
    - pip3 install -r requirements.txt
  artifacts:
    paths:
      - .env
# server:deploy:
#   stage: deploy_server_stage
#   image: python:3.9
#   environment: production
#   script: echo "Not implemented yet"
