# Generated by Django 4.1.7 on 2023-04-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_priority'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='locations',
            field=models.ManyToManyField(related_name='trips', to='places.place'),
        ),
    ]
