# Generated by Django 4.1.7 on 2023-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_options'),
        ('trips', '0003_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='locations',
            field=models.ManyToManyField(to='places.place'),
        ),
    ]
