# Generated by Django 4.1.7 on 2023-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shortened_url',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
