# Generated by Django 4.1.7 on 2023-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_shortened_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
