- hosts: server
  become: true
  become_method: sudo
  remote_user: mipu7431
  vars_files:
    - variables.yml
  tasks:
    - name: install postgressql packages
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - python3-psycopg2
        - libpq-dev
        - acl
    - name: ensure postgres is running
      service: name=postgresql state=started enabled=yes
    - name: Create the database
      postgresql_db: name="{{ db_name }}"
        state=present
      become: yes
      become_user: postgres
    - name: Ensure user has access to the database
      become: true
      become_user: postgres
      postgresql_user: db="{{ db_name }}"
        name="{{ db_user }}"
        password="{{ db_password }}"
        priv=ALL
        state=present
    - name: Ensure user does not have unnecessary permissions
      become: yes
      become_user: postgres
      postgresql_user: name="{{ db_user }}"
        role_attr_flags=NOSUPERUSER,NOCREATEDB
        state=present
    - name: Enable remote connection
      lineinfile:
        path: /etc/postgresql/13/main/postgresql.conf
        line: listen_addresses='*'
    - name: Enable remote connection for test user
      lineinfile:
        path: /etc/postgresql/13/main/pg_hba.conf
        line: 'host all url-manager 0.0.0.0/0 md5'
    - name: restart postgres
      service: name=postgresql state=restarted
